apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollystack

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - redis.yaml
  - collector.yaml
  - api-server.yaml
  - web-ui.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.0"
